examples:
  - example/*
  - example/**/*

use-paginator:
  - packages/use-pagination/*
  - packages/use-pagination/**/*

paginator:
  - packages/paginator/*
  - packages/paginator/**/*

repo:
  - ./*
